### post message
POST http://localhost:8080/sendToQueue?queue=q.test1
Content-Type: application/json

{
  "name": "[sendToQueue]: Hello Rabbitmq 1",
  "age": 20
}


### post Direct message
POST http://localhost:8080/sendDirect?exchange=ex.test.direct&routingKey=rk1
Content-Type: application/json

{
  "name": "[Direct]: Hello Rabbitmq 2",
  "age": 20
}

### post Fanout message
POST http://localhost:8080/sendFanout?exchange=ex.test.fanout
Content-Type: application/json

{
  "name": "[Fanout]: Hello Rabbitmq 1",
  "age": 20
}


### post Topic message
POST http://localhost:8080/sendTopic?exchange=ex.test.topic&routingKey=weather.sport.london.news
Content-Type: application/json

{
  "name": "[sendTopic]: Hello Rabbitmq 1",
  "age": 20
}

### post Header message // json
POST http://localhost:8080/sendHeaders?exchange=ex.test.header
Content-Type: application/json

{
  "headers": {
    "sport": "true",
    "age": "20"
  },
  "message": {
    "name": "[sendHeader]: Hello RabbitMQ 1",
    "age": 20
  }
}







### alternate post Header2 message
POST http://localhost:8080/sendHeaders2?exchange=ex.test.header
Content-Type: application/json

{
  "headers": {
    "sport": "true",
    "age": "20"
  },
  "message": {
    "name": "[sendHeader]: Hello RabbitMQ 1",
    "age": 20
  }
}
